[TEST-123] Nuestro test

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -6,13 +6,18 @@ if [ -z "$BRANCHES_TO_SKIP" ]; then
   BRANCHES_TO_SKIP="master develop"
 fi
 
-BRANCH_NAME="$(git symbolic-ref --short HEAD | sed -n 's/.*\(TEST-[0-9]*\).*/[\1]/p')"
+BRANCH_NAME="$(git symbolic-ref --short HEAD | sed -n 's/.*\(TEST-[0-9]\+\).*/[\1]/p')"
+
+# Validar que BRANCH_NAME no esté vacío
+if [ -z "$BRANCH_NAME" ]; then
+  echo "Error: BRANCH_NAME is empty or invalid."
+  exit 1
+fi
 
 BRANCH_NAME="${BRANCH_NAME##*/}"
 
 is_branch_excluded() {
   result=0
-
   for branch in ${BRANCHES_TO_SKIP}; do
     if [ "$branch" = "$BRANCH_NAME" ]; then
       result=1
@@ -22,7 +27,7 @@ is_branch_excluded() {
 }
 
 is_branch_in_commit_msg() {
-  head -1 "$COMMIT_MSG_FILE" | grep -c --regexp=^"${1}".*$
+  head -1 "$COMMIT_MSG_FILE" | grep -c "^${1}.*$"
 }
 
 if [ -n "$BRANCH_NAME" ] && ! [ "$(is_branch_excluded "$BRANCH_NAME")" -eq 1 ] && \
